package fr.olympa.api.redis;

public enum RedisChannel {

	BUNGEE_ASK_SEND_OLYMPAPLAYER,
	BUNGEE_SEND_OLYMPAPLAYER,
	BUNGEE_SEND_SERVERNAME,
	BUNGEE_SEND_SERVERSINFOS,

	SPIGOT_ASK_SERVERNAME,
	SPIGOT_SEND_OLYMPAPLAYER,
	SPIGOT_PLAYER_HAS_GROUP_CHANGED,
	SPIGOT_SERVER_SHUTDOWN,
	SPIGOT_PLAYER_SWITCH_SERVER,

	;
}
