chat:
  insult:
    - ez
    - fdp
    - pd
    - tg
    - ptn
    - niq
    - niqu
    - nique
    - niques
    - nik
    - nike
    - nikes
    - ftg
    - con
    - fdp
    - ntm
    - tepu
    - anal
    - fuck
    - bite
    - suce
    - suces
    - suceur
    - suceurs
    - suck
    - noob
    - pt1
    - put1
    - putain
    - merde
    - '|kiko'
    - '|batar'
    - '|fiot'
    - zbeub
    - salo
    - salau
    - salaud
    - salaut
    - salopar
    - salopard
    - salopart
    - '|connar'
    - chatteself
    - chate
    - enculer
    - foutre
    - pedale
    - couille
    - couile
    - '|encule'
    - '|bougnoul'
    - '|baltring'
    - leuleu
    - levrette
    - '|sodomi'
    - '|abruti'
    - '|branle'
    - '|emmerde'
    - '|gogol'
    - put
    - pute
    - putes
    - msk
    - miskine
  linkwhitelist:
    - olympa.net
    - youtube
    - discord
